version: "3.8"

services:
  poc-ho:
    hostname: poc-ho      
    container_name: iris-poc-ho
            
    image: containers.intersystems.com/intersystems/irishealth-ml:2023.1.4.580.0
    
    environment:
      - ISC_DATA_DIRECTORY=/db/pocho
      - ISC_CPF_MERGE_FILE=/merge/cpfmerge.cpf
    
    networks:
      - rede
  
    ports:
      - "1972:1972"
      - "52773:52773"

    volumes:
      - ./external/database:/db
      - ./external/cpf:/merge
      - ./build/iris.script:/build/iris.script
      - type: bind
        source: ./external/license/iris.key
        target: /license/iris.key

    
    command: 
      --key /license/iris.key 
       #-a /build/iris.script
  
networks:
  rede:
    name: docker-rede
    # IPAddress: 172.1.3.2
    external: true

