version: "3.8"

services:
  poc-ho:
    hostname: poc-ho      
    container_name: iris-poc-ho
    image: containers.intersystems.com/intersystems/irishealth:2023.1
    networks:
      - rede
  
    ports:
      - "1972:1972"
      - "22773:52773"
      - "2188:2188"

    volumes:
  
      - type: bind
        source: ./external/license/iris.key
        target: /license/iris.key

    
    command: 
      --key /license/iris.key 
      # -a /scripts/main.script


  
networks:
  rede:
    name: docker-rede
    # IPAddress: 172.1.3.2
    external: true

